.Dd $Mdocdate$
.Dt asmctl 1
.Os
.Sh NAME
.Nm asmctl
.Nd controlling keyboard backlight and LCD backlight
.Sh SYNOPSIS
.Nm asmctl Ar video
.Op Ar up | down | acpi
.Br
.Nm asmctl Ar key
.Op Ar up | down
.Sh DESCRIPTION
The
.Nm
command controls LCD backlight and keyboard backlight
by setting following sysctl variables.

.Dl hw.acpi.video.lcd0.brightness
.Dl dev.asmc.0.light.control

.Sh OPTIONS
.Bl -tag -width indent
.It Ar video up
LCD backlight more bright.
.It Ar video down
LCD backlight less dark.
.It Ar video acpi
switch LCD backlight brightness for AC powerd or Battery powered, depends on acpi status.
.It Ar key up
keyboard backlight more bright.
.It Ar key down
keybaord backlight less dark.
.El

.Sh FILES
.Bl -tag -width indent
.It Ar /var/lib/asmctl.conf
Saved sysctl variables for next boot.
.El

.Sh REQUIERMENT

Following kernel modules are required.

.Dl asmctl.ko
.Dl acpi_video.ko

.Sh SECURITY
Changing hw.acpi.video.* sysctl variables requires root privilege.
For this reason,
.Nm
is installed with setuid root.
On FreeBSD-11.0R or higher,
.Nm
uses capsicum(4) to be sandboxed.
