.Dd $Mdocdate$
.Dt asmctl 1
.Os
.Sh NAME
.Nm asmctl
.Nd controlling keyboard backlight and LCD backlight
.Sh SYNOPSIS
.Nm asmctl Ar video
.Op Ar up | down | acpi
.Br
.Nm asmctl Ar key
.Op Ar up | down
.Sh DESCRIPTION
The
.Nm
command controls LCD backlight and keyboard backlight
by setting following sysctl(8) variables.

.Dl hw.acpi.video.lcd0.brightness
.Dl dev.asmc.0.light.control

.Sh OPTIONS
.Bl -tag -width indent
.It Ar video up
Brighten the LCD backlight.
.It Ar video down
Dim the LCD backlight
.It Ar video acpi
Adjust the LCD backlight brightness based on whether the laptop is on AC power or battery power.  Relies on acpi status.
.It Ar key up
Brighten the keyboard backlight.
.It Ar key down
Dim the keyboard backlight.
.El

.Sh FILES
.Bl -tag -width indent
.It Ar /var/lib/asmctl.conf
Saved sysctl(8) values for next boot.
.El

.Sh REQUIERMENTS

The following kernel modules are required.

.Dl asmctl.ko
.Dl acpi_video.ko

.Sh SECURITY
Changing hw.acpi.video.* sysctl variables requires root privilege.
For this reason,
.Nm
is installed with setuid root.
On FreeBSD-11.0R or higher,
.Nm
uses capsicum(4) to be sandboxed.
